// <auto-generated />
using System;
using Biblioteca_App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca_Deheza_Segovia.Migrations
{
    [DbContext(typeof(Biblioteca))]
    partial class BibliotecaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Biblioteca_App.EstadoPrestamo", b =>
                {
                    b.Property<int>("EstadoPrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstadoPrestamoId");

                    b.ToTable("EstadosPrestamo");

                    b.HasData(
                        new
                        {
                            EstadoPrestamoId = 1,
                            Nombre = "Activo"
                        },
                        new
                        {
                            EstadoPrestamoId = 2,
                            Nombre = "Devuelto"
                        },
                        new
                        {
                            EstadoPrestamoId = 3,
                            Nombre = "Vencido"
                        });
                });

            modelBuilder.Entity("Biblioteca_App.EstadoReserva", b =>
                {
                    b.Property<int>("EstadoReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstadoReservaId");

                    b.ToTable("EstadosReserva");

                    b.HasData(
                        new
                        {
                            EstadoReservaId = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            EstadoReservaId = 2,
                            Nombre = "Cumplida"
                        },
                        new
                        {
                            EstadoReservaId = 3,
                            Nombre = "Cancelada"
                        });
                });

            modelBuilder.Entity("Biblioteca_App.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CantidadCopias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ISBN");

                    b.ToTable("Libros");

                    b.HasData(
                        new
                        {
                            ISBN = "978-0062316097",
                            Autor = "Yuval Noah Harari",
                            CantidadCopias = 3,
                            Genero = "Ensayo",
                            Titulo = "Sapiens"
                        },
                        new
                        {
                            ISBN = "978-0345539434",
                            Autor = "Carl Sagan",
                            CantidadCopias = 2,
                            Genero = "Ciencia",
                            Titulo = "Cosmos"
                        },
                        new
                        {
                            ISBN = "978-8437604572",
                            Autor = "Julio Cortazar",
                            CantidadCopias = 1,
                            Genero = "Novela",
                            Titulo = "Rayuela"
                        });
                });

            modelBuilder.Entity("Biblioteca_App.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoPrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MontoMulta")
                        .HasColumnType("REAL");

                    b.Property<int>("NroSocio")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrestamoId");

                    b.HasIndex("EstadoPrestamoId");

                    b.HasIndex("ISBN");

                    b.HasIndex("NroSocio");

                    b.ToTable("Prestamos");

                    b.HasData(
                        new
                        {
                            PrestamoId = 1,
                            EstadoPrestamoId = 1,
                            FechaPrestamo = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ISBN = "978-8437604572",
                            MontoMulta = 0.0,
                            NroSocio = 1003
                        });
                });

            modelBuilder.Entity("Biblioteca_App.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoReservaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NroSocio")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservaId");

                    b.HasIndex("EstadoReservaId");

                    b.HasIndex("ISBN");

                    b.HasIndex("NroSocio");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Biblioteca_App.Socio", b =>
                {
                    b.Property<int>("NroSocio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoSocioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NroSocio");

                    b.HasIndex("TipoSocioId");

                    b.ToTable("Socios");

                    b.HasData(
                        new
                        {
                            NroSocio = 1001,
                            Activo = true,
                            Apellido = "Fernandez",
                            Email = "lucia@mail.com",
                            Nombre = "Lucia",
                            TipoSocioId = 1
                        },
                        new
                        {
                            NroSocio = 1002,
                            Activo = true,
                            Apellido = "Gomez",
                            Email = "martin@mail.com",
                            Nombre = "Martin",
                            TipoSocioId = 1
                        },
                        new
                        {
                            NroSocio = 1003,
                            Activo = true,
                            Apellido = "Diaz",
                            Email = "carolina@mail.com",
                            Nombre = "Carolina",
                            TipoSocioId = 1
                        },
                        new
                        {
                            NroSocio = 1004,
                            Activo = true,
                            Apellido = "Lopez",
                            Email = "diego@mail.com",
                            Nombre = "Diego",
                            TipoSocioId = 2
                        },
                        new
                        {
                            NroSocio = 1006,
                            Activo = false,
                            Apellido = "Ramirez",
                            Email = "federico@mail.com",
                            Nombre = "Federico",
                            TipoSocioId = 1
                        });
                });

            modelBuilder.Entity("Biblioteca_App.TipoSocio", b =>
                {
                    b.Property<int>("TipoSocioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiasPrestamo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxLibros")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MultaPorDia")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TipoSocioId");

                    b.ToTable("TiposSocio");

                    b.HasData(
                        new
                        {
                            TipoSocioId = 1,
                            DiasPrestamo = 14,
                            MaxLibros = 3,
                            MultaPorDia = 50.0,
                            Nombre = "Estandar"
                        },
                        new
                        {
                            TipoSocioId = 2,
                            DiasPrestamo = 21,
                            MaxLibros = 6,
                            MultaPorDia = 30.0,
                            Nombre = "Premium"
                        });
                });

            modelBuilder.Entity("Biblioteca_App.Prestamo", b =>
                {
                    b.HasOne("Biblioteca_App.EstadoPrestamo", "EstadoPrestamo")
                        .WithMany("Prestamos")
                        .HasForeignKey("EstadoPrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca_App.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca_App.Socio", "Socio")
                        .WithMany("Prestamos")
                        .HasForeignKey("NroSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoPrestamo");

                    b.Navigation("Libro");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Biblioteca_App.Reserva", b =>
                {
                    b.HasOne("Biblioteca_App.EstadoReserva", "EstadoReserva")
                        .WithMany("Reservas")
                        .HasForeignKey("EstadoReservaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca_App.Libro", "Libro")
                        .WithMany("Reservas")
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Biblioteca_App.Socio", "Socio")
                        .WithMany("Reservas")
                        .HasForeignKey("NroSocio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoReserva");

                    b.Navigation("Libro");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("Biblioteca_App.Socio", b =>
                {
                    b.HasOne("Biblioteca_App.TipoSocio", "TipoSocio")
                        .WithMany("Socios")
                        .HasForeignKey("TipoSocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoSocio");
                });

            modelBuilder.Entity("Biblioteca_App.EstadoPrestamo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("Biblioteca_App.EstadoReserva", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Biblioteca_App.Libro", b =>
                {
                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Biblioteca_App.Socio", b =>
                {
                    b.Navigation("Prestamos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Biblioteca_App.TipoSocio", b =>
                {
                    b.Navigation("Socios");
                });
#pragma warning restore 612, 618
        }
    }
}
